server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1?useUnicode=true&characterEncoding=utf8
    username: root
    password: Qq131466



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ymsd.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl

#pagehelper分页插件配置 以下属性不加也可以实现分页功能
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


out_put_path: F:\\xm2\\Parent\\backend\\src\\main\\resources\\static\\
report _put_path: F:\\xm2\\Parent\\backend\\src\main\\resources\\template\\